version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: alas-system-frontend/Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - auth-service
      - proxy-service

  auth-service:
    build:
      context: .
      dockerfile: backend/Dockerfile.auth
    ports:
      - "6200:6200"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  proxy-service:
    build:
      context: .
      dockerfile: backend/Dockerfile.proxy
    ports:
      - "6300:6300"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - auth-service
