FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends android-tools-adb && \
    rm -rf /var/lib/apt/lists/*

COPY backend/proxy_service.py .
COPY backend/requirements-proxy.txt ./requirements.txt
COPY backend/scrcpy-server.jar .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 6300
CMD ["uvicorn", "proxy_service:app", "--host", "0.0.0.0", "--port", "6300"]
