FROM python:3.11-slim
WORKDIR /app
COPY backend/proxy_service.py .
COPY backend/requirements-proxy.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install cryptography
EXPOSE 6300
CMD ["python", "proxy_service.py"]
