FROM python:3.11-slim

# 工作目录
WORKDIR /app

# 复制 backend 目录到容器内
COPY backend/ .

# 安装依赖
COPY backend/requirements-auth.txt ./requirements.txt

RUN apt-get update && \
    apt-get install -y sshpass && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

# 暴露 API 端口
EXPOSE 6200

# 使用 uvicorn 启动 FastAPI 服务
CMD ["uvicorn", "auth_service:app", "--host", "0.0.0.0", "--port", "6200"]
